### ISSUE TITLE
Cường - Xoá folder .vscode và file build.rar

### ISSUE THREAD

**Issue by longhypepoly** [hypepoly-internship-2022/test-quoc-cuong#2]
Yêu cầu:
- Xoá folder `.vscode` và file `build.rar` trên nhánh develop.
- Update file `.gitignore` với content từ https://gist.github.com/longhypepoly/85e226869551b19dc713fdb0afc62a08

**Comment by chimpuchim** [comment]
h e mới thấy @@

**Comment by longhypepoly** [comment]
💯
